default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pgs-poker_development


test:
  <<: *default
  database: pgs-poker_test


production:
  <<: *default
  database: pgs-poker_production
  username: ppasciak
  password: piotrek123